version: '2'

services:
  python36:
    image: artsalliancemedia/thunderstorm-library:develop
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /var/app

    command: make test
    volumes:
      - ./:/var/app
    environment:
      - DB_NAME=test_auth_lib_py36
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
